"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {RecoilRoot} from 'recoil';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <RecoilRoot>
    <html lang="en">
    <head>
        <title>leet code</title>
        <meta name='description' content='Description' />
      </head>
      <body  suppressHydrationWarning={true} className={inter.className}>{children}</body>
    </html>
      </RecoilRoot>
  )
}
